### ISSUE TITLE
Multiple plugins on same WP install fail to update

### ISSUE THREAD

**Issue by matteo-tonini** [rayman813/smashing-plugin#6]
I have several plugins using this class and some of them are active on the same WP site.

When updating, if I select more than one plugin, the update fails in two occasion:
- when selecting the plugins, then "Bulk Action" > "Update" > "Apply"
- when clicking on "update now" on each plugin
In both cases the first plugin in the table updates correctly, 
while the others return "Update Failed: Plugin update failed."

When updating from "wp-admin/update-core.php", the plugins update properly instead.

I have made few adaptation to the class in order to make it work with several plugins on same site, 
but I still can't solve this problem.
Any suggestion?

**Comment by rayman813** [comment]
I expect you may be experiencing a race condition for the hooks. I doubt you are still in need of this fix by this point but in case anyone else is having this issue, my suggestion would be to set up a queue in the session to collect all of the items you want to update and instead of having your hooks fire immediately, have them add your updated plugins to the queue. Then run all of your hooks at once on all of the items in the queue.
